# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Strawberry Girl
email: fatima@kidocode.com
description: > # this means to ignore newlines until "baseurl:"
  This is my very first blog in using Jekyll I hope the journey to be awesome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fahtima.github.io/" # the base hostname & protocol for your site
twitter_username: Princessbatouly
github_username:  fahtima

# Build settings
markdown: kramdown
